#+INFOJS_OPT: view:info toc:4 sdepth:4
#+OPTIONS: H:6 toc:4

* About

Very short notes

Sudelbuch

* 2015
** 2015-03 March
*** 2015-03-13 Friday
**** start
 :PROPERTIES:
 :DATE: <2015-03-13 Fri 23:57>
 :END:
: git push -u origin gh-pages
*** 2015-03-14 Saturday
**** Fauré Quintet Nr 1: d
 :PROPERTIES:
 :DATE: <2015-03-14 Sat 08:56>
 :END:
*** 2015-03-15 Sunday
**** Animal Refrains / Silence and Repetition
 :PROPERTIES:
 :DATE: <2015-03-15 Sun 08:42>
 :END:
**** The virtue of pausing
 :PROPERTIES:
 :DATE: <2015-03-15 Sun 11:28>
 :END:

http://vitagate.ch/de/gesund_leben/konzentration/pausen

Konzentration

Gönnen Sie Ihrem Gehirn eine Pause
Das Gehirn erholt sich im Schlaf. Klar. Aber nicht nur. Auch im Wachzustand sind regelmässige Pausen wichtig.

Regelmässige Pausen sind keine verlorene Zeit.
Regelmässige Pausen sind keine verlorene Zeit.
© Petra Grau / pixelio.de
Wer geistig über längere Zeit unter Strom steht, sollte immer wieder kleine oder auch längere Erholungsphasen einbauen. Das ist kein unnötiger Zeitverlust, im Gegenteil. Nichtstun ist eine wichtige Voraussetzung für Kreativität und Produktivität. Wer sein Potential nutzen will, muss ausruhen, die Gedanken schweifen lassen. Nur gönnen die Menschen sich viel zu wenige Pausen.

Kreativitätsforscher Ernst Pöppel, Chef des Münchner Instituts für Medizinische Psychologie (IMP), spricht gar von einem «Kreativitätsstau». Pöppel ist überzeugt, dass unsere Gesellschaft «geradezu explodieren könnte, wenn alle täglich eine Stunde aus dem Kommunikationszwang aussteigen würden».

Mach mal Pause!
Folgende Arten von Pausen haben sich für Studierende bewährt. In angepasster Form haben sie auch im Arbeitsprozess Gültigkeit:

Kurze Gedankenpausen/Verschnaufpausen: Damit können Sie Gelerntes abschliessen und die Verarbeitungsprozesse im Gehirn fangen an.
Minipausen: 5 Minuten alle 30 Minuten: kurz aufzustehen, einige Bewegungsübungen machen.
Kurzpausen: Spätestens nach 2 Stunden lernen/arbeiten sollten Sie 15 bis 20 Minuten Pause machen. Tun Sie nichts ausser etwas trinken und vielleicht etwas (leichtes) essen.
Freizeitpausen: Nach 3 bis 4 Stunden lernen/arbeiten sollten Sie sich 1 bis 2 Stunden lang erholen und diese freie Zeit bewusst geniessen.
Nützliche Links:

_ Schweizerische Hirnliga

_ Verband für Gedächtnistraining

Download (pdf):

_ Merkblatt Brainfood
Wundermittel Schlaf
Das wichtigste für ein leistungsfähiges Gehirn ist die regelmässige Nachtruhe. Das Gehirn nutzt und braucht den Schlaf, um zu verarbeiten, was es tagsüber geleistet hat. Mehr noch. Viele Probleme lösen sich geradezu über Nacht. Viele Menschen kommen beim Aufwachen oft auf Lösungen, die ihm am Vortag noch unlösbar schienen. Schlafforscher erklären das Phänomen so: Der Schlaf dient dazu, überflüssige Nervenverknüpfungen abzubauen und neue zu festigen. Im Schlaf überführt das Gehirn zudem neue Informationen vom Zwischenspeicher ins Langzeitgedächtnis verankert sie da.

Sport treiben und gesund essen
Das Gehirn kann sich aber auch aktiv erholen. Sport kann Ihnen helfen, Ihre Konzentration zu verbessern. Denn Sport kurbelt nicht nur den Stoffwechsel an, sondern verbessert auch die Sauerstoffzufuhr, was der Konzentrationsfähigkeit dient.

Wichtig für das Gehirn ist auch eine gesunde Ernährung. Am besten sind fünf kleinere Mahlzeiten regelmässig über den Tag verteilt. So bleibt Ihr Blutzuckerspiegel stabil. Denn ein tiefer Blutzuckerspielge führt zu Konzentrationsmangel und Leistungsabfall. Nebst genügend Kohlenhydraten, Eiweiss, Vitaminen und pflanzlichen ungesättigten Fetten braucht das Gehirn aber auch genügend Flüssigkeit wie Wasser, ungesüssten Tee oder verdünnte Fruchtsäfte. Lebensmittel, die besonders gut für Ihr Gehirn sind, finden Sie auf dem Merkblatt «Brainfood».

Nahrungsergänzungsmittel
Aufbau- und Vitaminpräparate sind eine sinnvolle Ergänzung zur ausgewogenen Ernährung. Vor allem, wenn beispielsweise nach einer Krankheit ein erhöhter Bedarf an Mineralien, Vitaminen und Spurenelementen besteht.

Vitamine: Vitamin C kann stimulieren. Die B-Vitamine unterstützen die Funktion des Nervensystems und setzen Energie aus Kohlenhydraten frei, die es für die korrekte Funktion der Hirnzellen braucht.
Pflanzliche Stoffe: Ginseng oder Ginkgo biloba können die Konzentration verbessern, indem sie die Durchblutung der Hirnzellen fördern. Bestimmte Lebensmittel respektive Gewürze wie Knoblauch, Zwiebeln, Kohl oder Cayennepfeffer fördern ebenfalls die Durchblutung.
Kaffee, Guarana und Cola wirken wegen ihres Koffeingehaltes stimulierend.
Weitere Artikel zum Thema: Nicht alle Gehirnzellen sind ständig online | Das Geheimnis der grauen Zellen
**** ah hard links are treacherous - must copy per script.
 :PROPERTIES:
 :DATE: <2015-03-15 Sun 11:33>
 :END:

#+BEGIN_SRC sh
org-export html --infile sudel.org --outfile index.html
git checkout master
cp ~/Dropbox/000WORKFILES/0_PRIVATE/SUDEL.org ./
git add --all .
git commit -am "Updated on: `date`"
git push origin master
git checkout gh-pages
git merge master
git push origin gh-pages
git checkout master
#+END_SRC
